### ISSUE TITLE
The plugin work good on Android and Web Chrome Firefox - Doesn't work on iOS Safari

### ISSUE THREAD

**Issue by wytex** [creativecreatorormaybenot/microphone#31] opened 2022-08-02 06:59 UTC
I am trying to make it working on iOS Safari but still it doesnt work.
Very poor support for Audio recording for flutter on web.

**Comment by creativecreatorormaybenot** [comment] 2022-08-02 15:20
Duplicate of #14

**Closed as completed by creativecreatorormaybenot** 2022-08-02 15:20 UTC
