### ISSUE TITLE
i can't play the recorded audio on iOS

### ISSUE THREAD

**Issue by AbdullahGaber** [creativecreatorormaybenot/microphone#25] opened 2021-10-09 23:37 UTC
when i try to record audio it work correct on both of web and android , but when i try to use it on iOS it doesn't wok i hope you help me
this is the code that i use to store it in backend

`MultipartFile.fromBytes(
                  'audio.mp3',
                  filename: webFileName,
                )`
i also tried weba and oga but didn't work
Thanks in advance

**Comment by creativecreatorormaybenot** [comment] 2021-10-10 14:26
Duplicate of #14

**Closed as completed by creativecreatorormaybenot** 2021-10-10 14:26 UTC

**Comment by AbdullahGaber** [comment] 2021-10-10 14:33
@creativecreatorormaybenot  
nope , in my case iPhone app not safari browser ..

**Comment by AbdullahGaber** [comment] 2021-10-10 14:49
i hope you reopen the issue again

**Comment by creativecreatorormaybenot** [comment] 2021-10-10 16:23
@AbdullahGaber hi - the plugin is only supported on web currently:

![image](https://user-images.githubusercontent.com/19204050/136704587-997e3d51-2d74-44c0-a95f-00a8838dd426.png)

Feel free to contribute mobile support, though.

**Comment by AbdullahGaber** [comment] 2021-10-10 17:34
@creativecreatorormaybenot 
You mean that audio from plugin couldn't be played through iPhone app?

**Comment by creativecreatorormaybenot** [comment] 2021-10-10 17:40
@AbdullahGaber sorry, I am not sure what you mean.  
This is a plugin that supports Flutter web only at the moment.

**Comment by AbdullahGaber** [comment] 2021-10-10 17:43
@creativecreatorormaybenot 
i know, I uploaded the recorded file to backend with mp3 extension then try to play it through iPhone with just_audio package it couldn't be played

**Comment by creativecreatorormaybenot** [comment] 2021-10-10 17:51
@AbdullahGaber it is not an mp3.

You can check the file type on the blob object, see [`Blob.type`](https://api.flutter.dev/flutter/dart-html/Blob/type.html).

**Comment by AbdullahGaber** [comment] 2021-10-10 17:53
@creativecreatorormaybenot could you explain

**Comment by Shonu72** [comment] 2024-05-28 05:56
did you fiind any solution to play recorded audio in ios devices ?
